/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import SamplePlaying from "./compSample/SamplePlaying"
import SampleStore from "./compSample/SampleStore"
import ShaderTest from "./test/ShaderTest"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedauto";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="view/comm/FloatAd.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("compSample/SamplePlaying.ts",SamplePlaying);
        reg("compSample/SampleStore.ts",SampleStore);
        reg("test/ShaderTest.ts",ShaderTest);
    }
}
GameConfig.init();